"use strict";

export const LOGIN_ATTEMPT = "LOGIN_ATTEMPT";
export const LOGIN_FAILED = "LOGGED_FAILED";
export const LOGIN_SUCCESSFULLY = "LOGGED_SUCCESSFULLY";
export const LOGIN_RESET_CONTROL_VARS = "LOGIN_RESET_CONTROL_VARS";
export const LOGIN_LOGOUT = "LOGIN_LOGOUT";